export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_SINGLE_CUSTOMER = 'GET_SINGLE_CUSTOMER';
export const GET_ERRORS = 'GET_ERRORS';

//* Layout
export const CHANGE_SEARCH_MODAL_STATE = 'CHANGE_SEARCH_MODAL_STATE';